name: GCloud Storage Upload

on:
  workflow_run:
    workflows: ["Node.js CI"]  # Replace with the name of your main build workflow
    types:
      - completed

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v3
        with:
          name: react-build         
          path: dist/server/ 

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          install_components: gsutil

      - name: Sync files to GCS
        run: |
          if [ -d "dist/server/" ]; then
            gsutil -m rsync -r dist/server/ gs://survey-app-build/
          else
            echo "Directory dist/server/ does not exist."
            exit 1
          fi
