name: Deploy to GCloud Storage

on:
  workflow_run:
    workflows: [Build and Save Artifacts]
    types: [completed]
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Download build artifact
        id: download-artifact
        uses: dawidd6/action-download-artifact@v6
        with:
          run_id: ${{ github.event.workflow_run.id }}
          path: ./deployment
          name: react-build
          github_token: ${{ github.token }}
          repo: ${{github.repository}}
          search_artifact: true
          
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          install_components: gsutil

      - name: Sync versioned folder to Cloud Storage
        run: |
          VERSION=$(ls deployment)  # Get the version folder dynamically
          gsutil -m rsync -r deployment/${VERSION}/ gs://survey-app-build/${VERSION}/
