name: Deploy to GCloud Storage

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Download build artifact
        id: download-artifact
        uses: dawidd6/action-download-artifact@v6
        with:
          path: deployment
          name: react-build
          github_token: ${{ github.token }}
          repo: ${{github.repository}}
          workflow: main.yaml
          workflow_conclusion: completed
          
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          install_components: gsutil

      - name: Sync versioned folder to Cloud Storage
        run: |
          VERSION=$(ls deployment)  # Get the version folder dynamically
          gsutil -m rsync -r deployment/${VERSION}/ gs://survey-app-build/${VERSION}/
