name: Build and Deploy to GCloud Storage

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main" ]

jobs:
  build_and_upload:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v4.0.3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Generate date-based version
        id: version
        run: |
          VERSION=$(date +"%Y%m%d-%H%M%S")
          echo "VERSION=v${VERSION}" >> $GITHUB_ENV

      - name: Prepare deployment folder
        run: |
          mkdir -p deployment/${{ env.VERSION }}
          cp -r dist/ deployment/${{ env.VERSION }}/dist
          cp index.js deployment/${{ env.VERSION }}/

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          install_components: gsutil

      - name: Sync versioned folder to GCS
        run: |
          gsutil -m rsync -r deployment/${{ env.VERSION }}/ gs://survey-app-build/${{ env.VERSION }}/
